window.TeamMasterPrototypeData = {
  people: [
    {
      id: 'daniel',
      name: 'Daniel Qian',
      role: 'Founder / CEO',
      tone: 'calm',
      health: 86,
      bandwidth: 68,
      position: { x: 49, y: 18 },
    },
    {
      id: 'ivy',
      name: 'Ivy Chen',
      role: 'Legal Lead',
      tone: 'warning',
      health: 58,
      bandwidth: 120,
      position: { x: 79, y: 35 },
    },
    {
      id: 'marta',
      name: 'Marta Rossi',
      role: 'Finance Ops',
      tone: 'calm',
      health: 74,
      bandwidth: 81,
      position: { x: 71, y: 76 },
    },
    {
      id: 'ken',
      name: 'Ken Alvarez',
      role: 'Product Ops',
      tone: 'stable',
      health: 91,
      bandwidth: 57,
      position: { x: 25, y: 71 },
    },
    {
      id: 'sarah',
      name: 'Sarah Miller',
      role: 'Customer Lead',
      tone: 'stable',
      health: 80,
      bandwidth: 72,
      position: { x: 18, y: 32 },
    },
  ],
  projects: [
    {
      id: 'apollo',
      title: 'Swiss payroll launch',
      status: 'at-risk',
      progress: 64,
      ownerId: 'ivy',
      summary: 'Legal dependency is clear, but capacity is already above the safe line.',
      position: { x: 70, y: 31 },
      tasks: [
        { title: 'Confirm Swiss labor counsel', status: 'Needs owner' },
        { title: 'Review payroll processor contract', status: 'In progress' },
        { title: 'Prepare investor-safe launch note', status: 'Draft' },
      ],
    },
    {
      id: 'meridian',
      title: 'Meridian Group pilot',
      status: 'on-track',
      progress: 78,
      ownerId: 'sarah',
      summary: 'Customer team is ready, pending final evidence pack.',
      position: { x: 29, y: 48 },
      tasks: [
        { title: 'Send onboarding timeline', status: 'Ready' },
        { title: 'Collect procurement answers', status: 'Waiting' },
      ],
    },
    {
      id: 'atlas',
      title: 'Investor demo narrative',
      status: 'on-track',
      progress: 72,
      ownerId: 'daniel',
      summary: 'Presentation story is converging around command clarity and trust.',
      position: { x: 48, y: 76 },
      tasks: [
        { title: 'Tighten 90-second opening', status: 'Ready' },
        { title: 'Record prototype walkthrough', status: 'Next' },
      ],
    },
    {
      id: 'northstar',
      title: 'Operations scorecard',
      status: 'blocked',
      progress: 38,
      ownerId: 'ken',
      summary: 'Data shape is stable, but ownership signals are incomplete.',
      position: { x: 28, y: 76 },
      tasks: [
        { title: 'Map missing owners', status: 'Blocked' },
        { title: 'Normalize project labels', status: 'Next' },
      ],
    },
    {
      id: 'ledger',
      title: 'Runway forecast refresh',
      status: 'on-track',
      progress: 83,
      ownerId: 'marta',
      summary: 'Finance scenario is clear enough for board discussion.',
      position: { x: 73, y: 72 },
      tasks: [
        { title: 'Refresh hiring assumptions', status: 'Done' },
        { title: 'Prepare three runway cases', status: 'In progress' },
      ],
    },
  ],
  nexusFlow: [
    {
      id: 'input',
      label: 'Dashboard question',
      detail: 'Can we launch Swiss payroll next week without overloading legal?',
      kind: 'input',
      position: { x: 18, y: 26 },
      edges: ['thread'],
    },
    {
      id: 'thread',
      label: 'Create shared thread',
      detail: 'Context, attachments, and team signals enter one workspace.',
      kind: 'thread',
      position: { x: 38, y: 26 },
      edges: ['orchestrator'],
    },
    {
      id: 'orchestrator',
      label: 'Orchestration agent',
      detail: 'Routes the question to legal, finance, and operations context.',
      kind: 'agent',
      position: { x: 55, y: 42 },
      edges: ['legal', 'context'],
    },
    {
      id: 'legal',
      label: 'Legal agent',
      detail: 'Checks Swiss compliance, contract risk, and launch readiness.',
      kind: 'agent',
      position: { x: 74, y: 31 },
      edges: ['output'],
    },
    {
      id: 'context',
      label: 'Company context',
      detail: 'Bandwidth, prior cases, and customer commitments stay attached.',
      kind: 'context',
      position: { x: 70, y: 61 },
      edges: ['output'],
    },
    {
      id: 'output',
      label: 'Decision-ready output',
      detail: 'A short launch recommendation plus task assignments.',
      kind: 'output',
      position: { x: 49, y: 72 },
      edges: [],
    },
  ],
}
