// Orchestrates MiniMax-M3 to transcreate app/i18n/en.ts → app/i18n/zh.ts.
// I (the agent) DIRECT M3 via the brief below; M3 writes the Chinese.
//
//   node --experimental-strip-types scripts/i18n-zh.mjs
//
// Key/endpoint/model are read from eval-harness/.env (MINIMAX_*). Re-run after
// Danny edits en.ts. zh.ts is AUTO-GENERATED — hand-edits get overwritten.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");

// ── load MiniMax creds from eval-harness/.env ───────────────────────────────
const envPath = path.resolve(ROOT, "../eval-harness/.env");
const env = Object.fromEntries(
  fs.readFileSync(envPath, "utf8").split(/\r?\n/)
    .filter((l) => l.trim() && !l.startsWith("#") && l.includes("="))
    .map((l) => { const i = l.indexOf("="); return [l.slice(0, i).trim(), l.slice(i + 1).trim().replace(/^['"]|['"]$/g, "")]; })
);
const KEY = env.MINIMAX_API_KEY;
const BASE = env.MINIMAX_BASE_URL || "https://api.minimaxi.com/v1";
const MODEL = env.MINIMAX_MODEL || "MiniMax-M3";
if (!KEY) { console.error("No MINIMAX_API_KEY in eval-harness/.env"); process.exit(1); }

// ── load the English source (single source of truth) ───────────────────────
const { en } = await import(pathToFileURL(path.resolve(ROOT, "app/i18n/en.ts")).href);

// ── the director brief (approved) ───────────────────────────────────────────
const SYS = `你是 Avery 的资深中文文案。Avery 面向 20–500 人公司的管理者，定位是「资深前辈在你耳边」(a senior at your ear)——温暖、平实、站在用户这边、从不居高临下、不评判人，永远指向善意的下一步。绝不是 AI SaaS 效率工具 / 仪表盘 / 监控团队 的自夸腔。

任务：把给定 JSON 里的英文 value 转译（transcreation，不是直译）成自然、地道的中文，保持「前辈在耳边」的口吻。

铁律：
1. 只翻译 value；绝不改任何 key。返回 JSON 的结构、key 名、数组顺序、嵌套层级必须与输入完全一致。
2. 原样保留、不要翻译：品牌名 Avery；占位符 {em}（必须原样出现在 title 里）；所有数字/百分比/符号（如 45、20、47m、94%、3×、≠、$240K、18%、08:02、MMXXVI、20–500）；任何形如 risk / actions / performance 这种英文小写 logic key。
3. 红线：绝不给人打分 / 贴标签 / 「血条」；不用 VC 腔（the moat、auto-prioritized 之类）。
4. 术语：专家方法论用「Playbooks（沉淀下来的做法）」的口吻；不要把 Avery 说成仪表盘 / 指挥中心 / 盯着团队的工具。
5. 标题类（h2 / statement / kicker / em）要短、有力，符合中文标题习惯，别拖沓。
6. 只返回 JSON 本身，不要任何解释、不要 markdown 代码块围栏。`;

async function translateSection(name, obj) {
  const res = await fetch(`${BASE}/chat/completions`, {
    method: "POST",
    headers: { "Content-Type": "application/json", Authorization: `Bearer ${KEY}` },
    body: JSON.stringify({
      model: MODEL, temperature: 0.3, max_tokens: 6000,
      messages: [
        { role: "system", content: SYS },
        { role: "user", content: `区块名："${name}"。把下面 JSON 的英文 value 转译成中文，key 与结构完全一致，只返回 JSON：\n${JSON.stringify(obj, null, 2)}` },
      ],
    }),
  });
  if (!res.ok) throw new Error(`HTTP ${res.status} ${await res.text()}`);
  const data = await res.json();
  let txt = (data.choices?.[0]?.message?.content || "")
    .replace(/<think>[\s\S]*?<\/think>/g, "")
    .replace(/```(?:json)?/gi, "")
    .trim();
  const s = txt.indexOf("{"), e = txt.lastIndexOf("}");
  if (s < 0 || e < 0) throw new Error("no JSON in response");
  return JSON.parse(txt.slice(s, e + 1));
}

// ── translate all top-level sections with a small concurrency pool ──────────
const keys = Object.keys(en);
const zh = {};
const POOL = 4;
let idx = 0, failed = [];
async function worker() {
  while (idx < keys.length) {
    const k = keys[idx++];
    // M3 is a reasoning model and occasionally returns non-JSON for a complex
    // section; retry up to 3× before falling back to English (transient, so a
    // re-ask at temperature 0.3 almost always parses on the next try).
    let done = false, lastErr;
    for (let attempt = 1; attempt <= 3 && !done; attempt++) {
      try {
        zh[k] = await translateSection(k, en[k]);
        console.log(`✓ ${k}${attempt > 1 ? ` (retry ${attempt})` : ""}`);
        done = true;
      } catch (err) {
        lastErr = err;
      }
    }
    if (!done) {
      zh[k] = en[k]; // fall back to English for this section; safe + regenerable
      failed.push(k);
      console.log(`✗ ${k} — ${String(lastErr).slice(0, 120)} (kept English after 3 tries)`);
    }
  }
}
await Promise.all(Array.from({ length: POOL }, worker));

// ── force language-invariant fields back from en (logic keys, numbers, token) ─
zh.langSwitch = en.langSwitch;
if (zh.modules?.items) zh.modules.items.forEach((it, i) => { it.key = en.modules.items[i].key; });
if (zh.revenue?.kpis) zh.revenue.kpis.forEach((k, i) => { k.val = en.revenue.kpis[i].val; });
if (zh.morningBriefing?.stats) zh.morningBriefing.stats.forEach((s, i) => { s.num = en.morningBriefing.stats[i].num; });
if (zh.hero && !String(zh.hero.title).includes("{em}")) zh.hero.title = en.hero.title;

// ── write zh.ts ─────────────────────────────────────────────────────────────
const out = `import type { Dict } from "./index";

// AUTO-GENERATED by scripts/i18n-zh.mjs — MiniMax-M3 (${MODEL}) transcreation of en.ts.
// ⚠ Draft / 待 Danny 审字. Re-run the script after editing en.ts; hand-edits are overwritten.
export const zh: Dict = ${JSON.stringify(zh, null, 2)};
`;
fs.writeFileSync(path.resolve(ROOT, "app/i18n/zh.ts"), out, "utf8");
console.log(`\nWrote app/i18n/zh.ts (${keys.length - failed.length}/${keys.length} sections translated)` +
  (failed.length ? `; kept English for: ${failed.join(", ")}` : ""));
